# Generated by Django 4.0.6 on 2022-08-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='wallet',
            new_name='Wallet',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='trnsaction',
            new_name='transaction',
        ),
    ]
