# Generated by Django 4.0.6 on 2022-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transactions_remove_wallet_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='active',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
