# Generated by Django 4.0.6 on 2022-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_notifications_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='active',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_created',
            field=models.DateTimeField(default=None),
        ),
    ]
