# Generated by Django 4.0.6 on 2022-08-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_notifications_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='active',
        ),
    ]
