# Generated by Django 4.0.6 on 2022-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_notification_transaction_remove_transactions_wallet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
